export const NT_ORIG_LANG = 'el-x-koine'
export const NT_ORIG_LANG_BIBLE = 'ugnt'
export const OT_ORIG_LANG = 'hbo'
export const OT_ORIG_LANG_BIBLE = 'uhb'
export const ORIGINAL_SOURCE = 'ORIGINAL_SOURCE'
export const TARGET_LITERAL = 'TARGET_LITERAL'
export const TARGET_SIMPLIFIED = 'TARGET_SIMPLIFIED'

export const MANIFEST_NOT_FOUND_ERROR = 'This project manifest failed to load.  Please confirm that the correct manifest.yaml file exists in the project at:\n'
export const MANIFEST_INVALID_ERROR = 'The manifest for this project is invalid.  Project is at:\n'
export const BOOK_NOT_FOUND_ERROR = 'This book can not be found in the project.  Project is at:\n'
export const SCRIPTURE_NOT_FOUND_ERROR = 'There is no associated content for this verse.  Project is at:\n'
export const INVALID_URL = 'Invalid URL!'
export const INVALID_REPO_URL_ERROR = 'Invalid Project URL!'
export const REPO_NOT_FOUND_ERROR = 'Project not Found!'
export const MANIFEST_INVALID_SHORT_ERROR = 'The manifest for this project is invalid!'
export const LOADING_RESOURCE = 'Loading Resource...'
